name: Update README Activity

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README with Recent Activity
        uses: Readme-Workflows/recent-activity@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
